# Generated by Django 5.0.6 on 2024-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='tariff',
            field=models.CharField(default='FREE', max_length=300),
            preserve_default=False,
        ),
    ]
