# Generated by Django 5.0.6 on 2024-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_pack_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='tariff',
        ),
        migrations.AddField(
            model_name='pack',
            name='amount_per_month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
