# Generated by Django 5.0.6 on 2024-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_item_remove_pack_description_pack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
