# Generated by Django 5.0.6 on 2024-06-05 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_subscription_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='personalized_choices',
        ),
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.TextField(default='Damas, Yaounde, Cameroon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='company_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='company_type',
            field=models.CharField(choices=[('TPE', 'Très Petite Entreprise'), ('PMI', 'Petite et Moyenne Industrie'), ('PME', 'Petite et Moyenne Entreprise'), ('SU', 'StartUp'), ('autres', 'Autres')], default='Startup', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(default='lastName', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(default='620846169', max_length=15),
            preserve_default=False,
        ),
    ]
