# Generated by Django 5.0.6 on 2024-06-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0006_rename_user_name_subscription_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
