# Generated by Django 5.0.6 on 2024-06-05 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0007_alter_subscription_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='description',
        ),
        migrations.CreateModel(
            name='PackAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('advantage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packs.item')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packs.pack')),
            ],
        ),
    ]
