# Generated by Django 5.0.6 on 2024-06-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0008_remove_pack_description_packadvantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='description',
            field=models.ManyToManyField(to='packs.item'),
        ),
        migrations.DeleteModel(
            name='PackAdvantage',
        ),
    ]
