# Generated by Django 5.0.6 on 2024-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0009_pack_description_delete_packadvantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='amount_per_month',
            field=models.CharField(max_length=100),
        ),
    ]
