# Generated by Django 5.0.6 on 2024-06-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0010_alter_pack_amount_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_name',
            field=models.CharField(default='no name', max_length=100),
            preserve_default=False,
        ),
    ]
