# Generated by Django 5.0.6 on 2024-06-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0014_remove_subscription_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='items',
            field=models.ManyToManyField(blank=True, to='packs.item'),
        ),
    ]
