# Generated by Django 5.0.6 on 2024-06-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0015_subscription_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packs.pack'),
        ),
    ]
