# Generated by Django 5.0.6 on 2024-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0017_subscription_amount_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='amount_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
