# Generated by Django 5.0.6 on 2024-06-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0018_alter_pack_amount_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='amount_per_month',
            field=models.CharField(max_length=100),
        ),
    ]
