# Generated by Django 5.0.6 on 2024-06-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0020_eventitem_eventsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='category',
            field=models.CharField(choices=[('Event Brochure', 'Event Brochure'), ('Event Catalog', 'Event Catalog'), ('Event Promotion Campaign', 'Event Promotion Campaign'), ('Branding Rights', 'Branding Rights'), ('Logo Visibility', 'Logo Visibility')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
