# Generated by Django 5.0.6 on 2024-06-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0021_alter_eventitem_category_alter_eventitem_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventSubscription',
        ),
    ]
