# Generated by Django 5.0.6 on 2024-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0022_delete_eventsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('TPE', 'Très Petite Entreprise'), ('PMI', 'Petite et Moyenne Industrie'), ('PME', 'Petite et Moyenne Entreprise'), ('SU', 'StartUp'), ('autres', 'Autres')], max_length=10)),
                ('creation_date', models.DateField()),
                ('event_items', models.ManyToManyField(to='packs.eventitem')),
            ],
            options={
                'verbose_name': 'Event Subscription',
                'verbose_name_plural': 'Event Subscriptions',
            },
        ),
    ]
