# Generated by Django 5.0.6 on 2024-06-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0023_eventsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubscription',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
