# Generated by Django 5.0.6 on 2024-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0024_eventsubscription_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterField(
            model_name='eventsubscription',
            name='company_type',
            field=models.CharField(choices=[('TPE', 'Très Petite Entreprise'), ('PMI', 'Petite et Moyenne Industrie'), ('PME', 'Petite et Moyenne Entreprise'), ('StartUp', 'StartUp'), ('Autres', 'Autres')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company_type',
            field=models.CharField(choices=[('TPE', 'Très Petite Entreprise'), ('PMI', 'Petite et Moyenne Industrie'), ('PME', 'Petite et Moyenne Entreprise'), ('StartUp', 'StartUp'), ('Autres', 'Autres')], max_length=10),
        ),
    ]
