# Generated by Django 5.0.6 on 2024-06-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0026_subscription_name_alter_pack_amount_per_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
    ]
