# Generated by Django 5.0.6 on 2024-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0027_remove_subscription_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_first_name', models.CharField(max_length=200)),
                ('sponsor_last_name', models.CharField(max_length=200)),
                ('event_name', models.CharField(choices=[('Registration Desk', 'Registration Desk'), ('Delegate Lunches', 'Delegate Lunches'), ('Delegate Coffee Breaks', 'Delegate Coffee Breaks'), ('Networking Dinner', 'Networking Dinner'), ('Closing Reception', 'Closing Reception'), ('Lanyards & Badges', 'Lanyards & Badges')], max_length=200)),
                ('support_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'verbose_name': 'Sponsor Event',
                'verbose_name_plural': 'Sponsor Events',
            },
        ),
    ]
